Feature/registrysupport
BjoernPetersen/MusicBot pull request #95
Opened 2020-07-10 14:47 UTC by FelixGail

Add interfaces to support online registration of the instance.

New interfaces:
 - `DomainHandler`: keeps track of ip addesses and domains the musicbot is accessible at
 - `Version`: Version information. Everything that should be available at /version

2020-07-14 17:06 UTC, BjoernPetersen commented on src/main/kotlin/net/bjoernpetersen/musicbot/spi/version/Version.kt
> +data class ImplementationInfo(val projectInfo: String, val name: String, val version: String)
Please include some docs on the arguments (you can copy them from the OpenAPI docs).

2020-07-14 17:07 UTC, BjoernPetersen commented on src/main/kotlin/net/bjoernpetersen/musicbot/spi/version/Version.kt
> + * Constains version information about the MusicBot instance
```suggestion
 * Contains version information about the MusicBot instance
```

2020-07-14 17:09 UTC, BjoernPetersen commented on src/main/kotlin/net/bjoernpetersen/musicbot/spi/version/Version.kt
> +interface Version {
Why is this an interface? Instances of this should always contain the exact content specified in the API docs, so I don't think it should be extended. Maybe make it a data class?

2020-07-14 17:10 UTC, BjoernPetersen commented on src/main/kotlin/net/bjoernpetersen/musicbot/spi/domain/DomainHandler.kt
> + * Keeps track of IpAddresses and Domains the MusicBot is accessible by.
```suggestion
 * Keeps track of IP addresses and domains the MusicBot is accessible by.
```

2020-07-14 17:11 UTC, BjoernPetersen commented on src/main/kotlin/net/bjoernpetersen/musicbot/spi/domain/DomainHandler.kt
> +     * Returns a map of IpAddress strings to domain names.
```suggestion
     * Returns a map of IP address strings to domain names.
```

2020-07-14 17:14 UTC, BjoernPetersen commented on src/main/kotlin/net/bjoernpetersen/musicbot/spi/domain/DomainHandler.kt
> +    val ipDomains: Map<String, String>
I like to call maps like this `domainByIp`, so the accessor syntax looks like that: `val domain = domainByIp["1.1.1.1"]`, which I personally find quite nice and clear.

2020-07-14 17:18 UTC, BjoernPetersen commented on src/main/kotlin/net/bjoernpetersen/musicbot/spi/domain/DomainHandler.kt
> +interface DomainHandler {
Shouldn't this interface have some sort of initialization method? As far as I understand, setting the domains up will take some time and involve some IO calls. Such time-consuming, blocking work should never happen in a constructor.

If there's an initialization function, the domain-ip-map should also probably not be a public property as it's not available for the whole lifetime of the object and throwing exceptions in property-getters is bad style.

2020-07-15 14:19 UTC, FelixGail commented on src/main/kotlin/net/bjoernpetersen/musicbot/spi/domain/DomainHandler.kt
> +interface DomainHandler {
How domains are acquired, and therefore the initialization, is of no concern for the core implementation.
The desktop implementation for example takes both a path and an URL as initialization parameters, this might however 
be different for other implementations.

I agree on the exception part.

2020-07-15 15:35 UTC, BjoernPetersen commented on src/main/kotlin/net/bjoernpetersen/musicbot/spi/version/Version.kt
> +    val version: String)
```suggestion
    val version: String
)
```

2020-07-15 15:41 UTC, BjoernPetersen commented on src/main/kotlin/net/bjoernpetersen/musicbot/spi/version/Version.kt
> +    val implementation: ImplementationInfo
```suggestion
 * Contains information about API version, name of the MusicBot instance and implementation information.
 *
 * @param apiVersion The API version.
 * @param botName A user-friendly name for the bot instance. May be customized per instance.
 * @param implementation Information about the implementation serving the API.
 */
data class VersionInfo(
    val apiVersion: String,
    val botName: String,
    val implementation: ImplementationInfo
```

2020-07-15 15:41 UTC, BjoernPetersen commented on src/main/kotlin/net/bjoernpetersen/musicbot/spi/version/Version.kt
> +    val implementation: ImplementationInfo
Same format for `ImplementationInfo` and `Version` please

2020-07-15 15:42 UTC, BjoernPetersen commented on src/main/kotlin/net/bjoernpetersen/musicbot/spi/version/Version.kt
> +data class Version (
What's this intermediate class for?

2020-07-15 15:43 UTC, BjoernPetersen commented on src/main/kotlin/net/bjoernpetersen/musicbot/spi/domain/DomainHandler.kt
> +interface DomainHandler {
If the implementation is tied to the caller, i.e. the DeskBot calls the DomainHandler implementation directly, that's okay.

2020-07-15 16:25 UTC, FelixGail commented on src/main/kotlin/net/bjoernpetersen/musicbot/spi/domain/DomainHandler.kt
> +interface DomainHandler {
It does. The implementation is only injected as DomainHandler to be available for plugins like the registry plugin.

2020-07-15 16:32 UTC, FelixGail commented on src/main/kotlin/net/bjoernpetersen/musicbot/spi/version/Version.kt
> +data class Version (
I didn't refactor the version class when I moved it from the deskbot. It serves no purpose in this case.

2020-07-15 17:34 UTC, FelixGail commented on src/main/kotlin/net/bjoernpetersen/musicbot/spi/version/Version.kt
> +data class Version(
On second thought. Having version as data class makes it hard to inject it, since it now is final. Can we revert this back to interface, or maybe class?

2020-07-15 18:51 UTC, BjoernPetersen commented on src/main/kotlin/net/bjoernpetersen/musicbot/spi/version/Version.kt
> +data class Version(
How is it hard to inject?

2020-07-16 12:40 UTC, FelixGail commented on src/main/kotlin/net/bjoernpetersen/musicbot/spi/version/Version.kt
> +data class Version(
Version needs information from the main config in the desk it, which is itself injected. So implementing or subclassing version ist the most straightforward way to inject version.

2020-11-07 12:59 UTC, BjoernPetersen requested changes

2020-11-07 12:59 UTC, BjoernPetersen commented on src/main/kotlin/net/bjoernpetersen/musicbot/spi/domain/DomainHandler.kt
> +     * Returns a map of Ip address strings to domain names.
```suggestion
     * Returns a map of IP address strings to domain names.
```

2020-11-07 12:59 UTC, BjoernPetersen commented on src/main/kotlin/net/bjoernpetersen/musicbot/spi/version/Version.kt
> +data class Version(
Your reasoning doesn't make sense to me. How is subclassing going to make instantiation easier?

2020-11-07 12:59 UTC, BjoernPetersen commented
Sorry for taking so long with this, I thought this PR was much more complicated.

2020-11-07 19:37 UTC, BjoernPetersen approved these changes

2020-11-07 19:38 UTC, merged